### ISSUE TITLE
Error while cancelling an order

### ISSUE THREAD

**Issue by lkesko1** [jimako1989/bitfinexpy#8]
Error while cancelling an order: 
`400 error_response : {'message': 'Key order_id was not present.'}`

Found a typo in this line: 
https://github.com/jimako1989/bitfinexpy/blob/e900c86db31ac47f4e4be57b3d0e072f0b30a3a8/bitfinexpy.py#L128

**Comment by tk42** [comment]
@lkesko1 Hi! thank you for reporting the typo. I've just merged the modification. If you found something suspicious, please let me know. ;)
